import {WIDTH,HEIGHT,FPS,FINAL_LEVEL,MAX_LIVES,BOSS_LEVELS,WEAPONS,GIFTS,GIFT_WEIGHTS,FLAMETHROWER_DAMAGE,COLORS} from './config.js';
import {AudioEngine} from './audio.js';
const C=COLORS;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rect=(x,y,w,h)=>({x,y,w,h});
const overlap=(a,b)=>a.x<b.x+b.w && b.x<a.x+a.w && a.y<b.y+b.h && b.y<a.y+a.h;
const rr=(x,y,w,h)=>({x:x-w/2,y:y-h/2,w,h});
const hitCircle=(r,x,y,rad)=>x>=r.x-rad&&x<=r.x+r.w+rad&&y>=r.y-rad&&y<=r.y+r.h+rad;
const weighted=(obj)=>{const es=Object.entries(obj),sum=es.reduce((a,[,v])=>a+v,0);let n=Math.random()*sum;for(const [k,w] of es){n-=w;if(n<=0)return k;}return es[0][0];};

export class Projectile{constructor(x,y,kind){this.x=x;this.y=y;this.kind=kind;this.speed={arrow:11,gun:15,bazooka:8,flamethrower:7}[kind];this.damage=WEAPONS[kind].damage;this.alive=true;}update(){this.y-=this.speed;if(this.y<-30)this.alive=false;}box(){const s={arrow:[8,24],gun:[8,18],bazooka:[14,32],flamethrower:[18,34]}[this.kind];return rr(this.x,this.y,s[0],s[1]);}}
export class EnemyBullet{constructor(x,y,vx,vy,boss=false,color=null){Object.assign(this,{x,y,vx,vy,boss,color,r:boss?6:5,alive:true});}update(){this.x+=this.vx;this.y+=this.vy;if(this.y>HEIGHT+20||this.y<-40||this.x<-40||this.x>WIDTH+40)this.alive=false;}box(){return rr(this.x,this.y,this.r*2,this.r*2);}}

class Enemy{constructor(x,y,w,h,hp,type,level){Object.assign(this,{x,y,w,h,hp,maxHp:hp,type,level,alive:true,flash:0,burnTimer:0,burnTick:0});this.score=0;}box(){return rr(this.x,this.y,this.w,this.h);}hitRects(){return [this.box()];}hit(d){this.hp-=d;this.flash=5;}ignite(){this.burnTimer=Math.max(this.burnTimer,90);}tint(col){return this.burnTimer>0&&this.flash<=0?C.orange:this.flash>0?C.white:col;}burn(g){if(this.burnTimer>0){this.burnTimer--;this.burnTick--;if(this.burnTick<=0){this.burnTick=15;g.damageEnemy(this,FLAMETHROWER_DAMAGE);}}}}
export class Shooter extends Enemy{constructor(l){super(Math.random()*(WIDTH-80)+40,-30,44,32,l<5?2:3,'shooter',l);this.targetY=60+Math.random()*210;this.dir=Math.random()<.5?-1:1;this.sway=Math.min(.6+.05*l,1.4);this.bulletSpeed=Math.min(2+.12*l,3.6);this.shootTimer=60+Math.random()*90;this.score=100;}update(g){if(this.flash)this.flash--;if(this.y<this.targetY)this.y+=1.3;else{this.x+=this.dir*this.sway;if(this.x<30||this.x>WIDTH-30)this.dir*=-1;}if(--this.shootTimer<=0){this.shootTimer=50+Math.random()*Math.max(50,230-this.level*10);g.fireAtPlayer(this.x,this.y+16,this.bulletSpeed);}}}
export class Drifter extends Enemy{constructor(l,target){super(30+Math.random()*(WIDTH-60),-120+Math.random()*90,36,36,l<6?1:2,'drifter',l);const dx=target-this.x,dy=HEIGHT-40-this.y,d=Math.hypot(dx,dy)||1,s=Math.min(1.3+.1*l,3);this.vx=dx/d*s;this.vy=dy/d*s;this.spin=Math.random()*Math.PI*2;this.score=50;}update(g){if(this.flash)this.flash--;this.x+=this.vx;this.y+=this.vy;this.spin+=.06;if(this.y>HEIGHT+40||this.x<-60||this.x>WIDTH+60){this.alive=false;g.missed++;}}}
export class Roller extends Enemy{constructor(l){const left=Math.random()<.7;super(left?-30:WIDTH+30,60+Math.random()*160,40,40,l<10?3:4,'roller',l);this.dir=left?1:-1;this.speed=Math.min(1.3+.06*l,2.6);this.angle=0;this.dropTo=null;this.score=150;}update(g){if(this.flash)this.flash--;if(this.dropTo!==null){this.y+=1.6;this.angle+=this.dir*.05;if(this.y>=this.dropTo)this.dropTo=null;}else{this.x+=this.dir*this.speed;this.angle+=this.dir*this.speed/20;this.y+=.1;if((this.dir===1&&this.x>WIDTH-25)||(this.dir===-1&&this.x<25)){this.dir*=-1;this.dropTo=this.y+70;}}if(this.y>HEIGHT+40){this.alive=false;g.missed++;}}}
export class Boss extends Enemy{constructor(l,type='boss'){super(WIDTH/2,-80,150,80,40+12*(Math.floor(l/3)-1),type,l);this.score=1000*Math.floor(l/3);this.t=0;this.rate=.02;this.sweep=0;this.entered=false;this.fireTimer=180+Math.random()*120;}get enraged(){return this.hp<=this.maxHp/2;}update(g){if(this.flash)this.flash--;if(!this.entered){this.y+=Math.min(1.4,Math.max(.35,(110-this.y)*.035));if(this.y<110)return;this.entered=true;}const target=this.enraged?.03:.02;this.rate+=(target-this.rate)*.03;this.t+=this.rate;this.sweep=Math.min(1,this.sweep+.012);const e=this.sweep*this.sweep*(3-2*this.sweep);this.x=WIDTH/2+Math.sin(this.t)*230*e;this.y=110+Math.sin(this.t*1.7)*15*e;if(--this.fireTimer<=0){const slow=Math.max(5,8-Math.floor(this.level/9));this.fireTimer=(3+Math.random()*(slow-3))*FPS;if(Math.random()<.6){const n=this.enraged?2:1,s=this.enraged?3.2:2.8;for(let i=-n;i<=n;i++){const a=Math.PI/2+i*.27;g.ebullets.push(new EnemyBullet(this.x,this.y+38,Math.cos(a)*s,Math.sin(a)*s,true));}}else for(const off of (this.enraged?[-.12,0,.12]:[-.06,.06]))g.fireAtPlayer(this.x,this.y+38,3.4,off,true);}}}
export class BabyOctopus extends Enemy{constructor(x,y,l,target){super(x,y,34,34,1,'baby',l);this.vx=Math.random()*2-1;this.vy=1.5;this.wander=Math.random()*7;this.life=720;this.targetX=target;this.score=120;}update(g){if(this.flash)this.flash--;if(--this.life<=0||this.y>HEIGHT+45){this.alive=false;g.missed++;return;}const dx=g.player.x-this.x,dy=g.player.y-this.y,d=Math.max(1,Math.hypot(dx,dy));const desiredX=dx/d*1.45,desiredY=Math.max(.75,dy/d*1.45);this.wander+=(Math.random()-.5)*.22;this.vx+=(desiredX+Math.sin(this.wander*1.7)*.75-this.vx)*.055;this.vy+=(desiredY+Math.cos(this.wander*1.25)*.28-this.vy)*.045;const sp=clamp(Math.hypot(this.vx,this.vy),1.15,2.15),cur=Math.hypot(this.vx,this.vy)||1;this.vx*=sp/cur;this.vy*=sp/cur;this.x=clamp(this.x+this.vx,20,WIDTH-20);this.y+=this.vy;}}
export class SpaceOctopus extends Boss{constructor(l){super(l,'octopus');this.hp=this.maxHp=46+10*(Math.floor(l/5)-1);this.score=1400+120*l;this.rate=.016;this.spamTimer=120+Math.random()*120;this.waveActive=false;}update(g){if(this.flash)this.flash--;if(!this.entered){this.y+=Math.min(1.4,Math.max(.35,(125-this.y)*.035));if(this.y<125)return;this.entered=true;}const target=this.enraged?.022:.016;this.rate+=(target-this.rate)*.03;this.t+=this.rate;this.sweep=Math.min(1,this.sweep+.012);const e=this.sweep*this.sweep*(3-2*this.sweep);this.x=WIDTH/2+Math.sin(this.t)*250*e;this.y=125+Math.sin(this.t*1.8)*22*e;this.spamTimer--;const babies=g.enemies.filter(x=>x.type==='baby'&&x.alive).length;if(this.waveActive&&babies===0){this.waveActive=false;this.spamTimer=120+Math.random()*240;}if(!this.waveActive&&this.spamTimer<=0){for(let i=0;i<3;i++)g.enemies.push(new BabyOctopus(this.x+(i-1)*24,this.y+38,this.level,g.player.x));this.waveActive=true;g.audio.sfx('octopus_spawn');}}}
export class Snake extends Boss{constructor(l){super(l,'snake');this.w=50;this.h=42;this.hp=this.maxHp=50+8*Math.floor(l/3);this.score=1500+100*l;this.t=0;this.y=-50;this.entered=false;this.history=[[this.x,this.y]];this.segments=Array.from({length:11},()=>[this.x,this.y]);this.venomTimer=120;this.bodyTimer=220;}hitRects(){return [this.box(),...this.segments.map(([x,y])=>rr(x,y,30,30))];}update(g){if(this.flash)this.flash--;if(!this.entered){this.y+=1.4;if(this.y>=190)this.entered=true;}else{this.t+=this.enraged?.024:.016;this.x=WIDTH/2+Math.sin(this.t)*300;this.y=190+Math.sin(this.t*2)*45;}this.history.unshift([this.x,this.y]);this.history.length=600;let seg=[],dist=0,need=26,px=this.history[0][0],py=this.history[0][1];for(let i=1;i<this.history.length&&seg.length<11;i++){const q=this.history[i],d=Math.hypot(q[0]-px,q[1]-py);dist+=d;px=q[0];py=q[1];while(dist>=need&&seg.length<11){seg.push([q[0],q[1]]);need+=26;}}while(seg.length<11)seg.push(this.history[this.history.length-1]);this.segments=seg;if(!this.entered)return;if(--this.venomTimer<=0){this.venomTimer=this.enraged?105:150;for(const off of (this.enraged?[-.25,0,.25]:[0]))g.fireAtPlayer(this.x,this.y+22,2.2,off,true,C.green);}if(--this.bodyTimer<=0){this.bodyTimer=this.enraged?140:200;const s=this.segments[Math.floor(Math.random()*this.segments.length)];g.ebullets.push(new EnemyBullet(s[0],s[1]+10,0,2,true,C.green));}}}

export class Player{constructor(){this.w=46;this.h=30;this.x=WIDTH/2;this.y=HEIGHT-40;this.speed=6;this.lives=3;this.cooldown=0;this.invuln=0;this.shield=0;this.shieldTotal=10*FPS;this.weapon='arrow';this.weaponTime=0;this.weaponTotal=1;this.laserOn=false;}box(){return rr(this.x,this.y,this.w,this.h);}hitbox(){return rr(this.x,this.y,this.w-12,this.h-6);}setWeapon(k,frames=1){this.weapon=k;this.weaponTime=this.weaponTotal=Math.max(1,frames);this.cooldown=0;}update(keys,g){if(keys.left)this.x-=this.speed;if(keys.right)this.x+=this.speed;this.x=clamp(this.x,this.w/2,WIDTH-this.w/2);this.laserOn=false;if(this.weapon!=='arrow'&&--this.weaponTime<=0)this.setWeapon('arrow');if(this.cooldown>0)this.cooldown--;if(keys.fire){if(this.weapon==='laser'||this.weapon==='flamethrower'){this.laserOn=true;if(g.tick%(this.weapon==='laser'?8:10)===0)g.audio.sfx(this.weapon);}else if(this.cooldown===0){g.arrows.push(new Projectile(this.x,this.y-20,this.weapon));g.audio.sfx(this.weapon);this.cooldown=WEAPONS[this.weapon].cooldown;}}if(this.invuln>0)this.invuln--;if(this.shield>0)this.shield--;}}

export class Pickup{constructor(kind,x,y){this.kind=kind;this.x=x;this.y=y;this.isWeapon=!!WEAPONS[kind];this.vy=this.isWeapon?1.6:(kind==='health'||kind==='shield'?1.8:2);this.t=Math.random()*Math.PI*2;this.alive=true;}get sx(){return this.x+Math.sin(this.t)*6;}update(){this.y+=this.vy;this.t+=.1;if(this.y>HEIGHT+30)this.alive=false;}box(){return rr(this.sx,this.y,40,40);}}

export class Game{
 constructor(){this.audio=new AudioEngine();this.high=Number(localStorage.getItem('spaceCarInvadersHigh')||0);this.state='menu';this.menuOpen=false;this.menuIndex=0;this.fullscreen=false;this.soundEnabled=true;this.tick=0;this.stars=Array.from({length:90},()=>({x:Math.random()*WIDTH,y:Math.random()*HEIGHT,sp:.3+Math.random()*1.7,sz:1+Math.floor(Math.random()*2)}));this.reset();}
 reset(){this.player=new Player();this.arrows=[];this.ebullets=[];this.enemies=[];this.pickups=[];this.particles=[];this.floaters=[];this.score=0;this.kills=0;this.missed=0;this.nextLifeAt=3000;this.playFrames=0;this.levelClearTimer=0;this.startLevel(1);}
 save(){if(this.score>this.high)this.high=this.score;localStorage.setItem('spaceCarInvadersHigh',String(this.high));}
 startLevel(n){this.level=n;this.ebullets=[];this.queue=[];this.bossesThisLevel=BOSS_LEVELS[n]||[];this.queue.push(...this.bossesThisLevel);const d=(n-1)/(FINAL_LEVEL-1);let shooters=n===FINAL_LEVEL?5:Math.min(3+Math.floor(8*d),11),drifters=n===FINAL_LEVEL?8:Math.min(4+Math.floor(12*d),16),rollers=n===FINAL_LEVEL?5:Math.min(1+Math.floor(5*d),6);if(this.bossesThisLevel.length){shooters=Math.max(2,shooters-1);drifters=Math.max(3,drifters-1);}this.queue.push(...Array(shooters).fill('shooter'),...Array(drifters).fill('drifter'),...Array(rollers).fill('roller'));this.queue.sort(()=>Math.random()-.5);this.spawnTimer=120;this.banner=120;this.levelFrames=0;this.levelClearTimer=0;this.player.setWeapon('arrow');this.player.shield=0;this.weaponSchedule=Array.from({length:1+Math.floor(Math.random()*3)},()=>300+Math.random()*2280).sort((a,b)=>a-b);this.healthSchedule=Math.random()<.33?[480+Math.random()*1920]:[];this.shieldSchedule=Math.random()<.28?[600+Math.random()*1920]:[];}
 get gameRunning(){return this.state==='play'||this.state==='paused';}
 menuItems(){const a=this.gameRunning?['Continue']:[];return [...a,'New Game',this.soundEnabled?'Sound: ON':'Sound: OFF',this.fullscreen?'Normal Mode':'Full Screen','Exit'];}
 openMenu(){if(this.state==='menu')return;this.menuOpen=true;this.menuIndex=0;if(this.state==='play')this.state='paused';}
 closeMenu(){this.menuOpen=false;if(this.state==='paused')this.state='play';}
 handleMenu(key){const items=this.menuItems();if(key==='escape'){this.closeMenu();return;}if(key==='up'||key==='w'){this.menuIndex=(this.menuIndex-1+items.length)%items.length;return;}if(key==='down'||key==='s'){this.menuIndex=(this.menuIndex+1)%items.length;return;}if(key!=='enter'&&key!=='space')return;const choice=items[this.menuIndex];if(choice==='Continue')this.closeMenu();else if(choice==='New Game'){this.reset();this.state='play';this.menuOpen=false;}else if(choice.startsWith('Sound')){this.audio.toggle();this.soundEnabled=this.audio.enabled;}else if(choice==='Full Screen'||choice==='Normal Mode'){this.fullscreen=!this.fullscreen;this.onFullscreen?.(this.fullscreen);}else if(choice==='Exit'){this.save();this.onExit?.();}}
 fireAtPlayer(x,y,speed,spread=0,boss=false,color=null){const a=Math.atan2(this.player.y-y,this.player.x-x)+spread;this.ebullets.push(new EnemyBullet(x,y,Math.cos(a)*speed,Math.sin(a)*speed,boss,color));}
 addScore(v){this.score+=v;if(this.score>=this.nextLifeAt){this.nextLifeAt+=3000;this.player.lives=Math.min(MAX_LIVES,this.player.lives+1);this.audio.sfx('extra_life');}if(this.score>this.high)this.high=this.score;}
 hurt(){if(this.player.shield>0||this.player.invuln>0)return;this.player.lives--;this.player.invuln=120;if(this.player.lives<=0){this.state='over';this.audio.sfx('death');this.audio.sfx('lose');this.save();}else this.audio.sfx('hurt');}
 damageEnemy(e,d){if(!e.alive)return;e.hit(d);if(e.hp<=0){e.alive=false;this.kills++;this.addScore(e.score);if(e.type==='boss'||e.type==='octopus'||e.type==='snake'){this.pickups.push(new Pickup('cake',e.x-35,e.y),new Pickup('pizza',e.x+35,e.y));}else if(Math.random()<.18){const k=weighted(GIFT_WEIGHTS);this.pickups.push(new Pickup(k,e.x,e.y));}}}
 spawnOne(){const k=this.queue.shift();if(k==='boss')this.enemies.push(new Boss(this.level));else if(k==='snake')this.enemies.push(new Snake(this.level));else if(k==='octopus')this.enemies.push(new SpaceOctopus(this.level));else if(k==='shooter')this.enemies.push(new Shooter(this.level));else if(k==='drifter')this.enemies.push(new Drifter(this.level,this.player.x));else this.enemies.push(new Roller(this.level));this.spawnTimer=k==='boss'||k==='snake'||k==='octopus'?150:Math.max(30,100-this.level*6);}
 collect(p){if(p.kind==='health'){if(this.player.lives>=MAX_LIVES)return;this.player.lives++;this.audio.sfx('health');}else if(p.kind==='shield'){this.player.shield=this.player.shieldTotal;this.audio.sfx('shield');}else if(p.isWeapon){this.player.setWeapon(p.kind,(10+Math.random()*10)*FPS);this.audio.sfx('pickup');}else{this.addScore(GIFTS[p.kind]||0);this.audio.sfx('pickup');}}
 rocketBlast(a,e){const r=100;this.audio.sfx('explosion');for(const x of this.enemies)if(x!==e&&x.alive&&x.hitRects().some(q=>Math.hypot(q.x+q.w/2-a.x,q.y+q.h/2-a.y)<=r+15))this.damageEnemy(x,6);for(const b of this.ebullets)if(Math.hypot(b.x-a.x,b.y-a.y)<=r)b.alive=false;}
 applyLaser(){if(this.player.weapon!=='laser'||!this.player.laserOn)return;const x=this.player.x;for(const b of this.ebullets)if(Math.abs(b.x-x)<10&&b.y<this.player.y)b.alive=false;this.laserTick=(this.laserTick||0)-1;if(this.laserTick<=0){this.laserTick=5;for(const e of this.enemies)if(e.alive&&e.hitRects().some(r=>x>=r.x-6&&x<=r.x+r.w+6&&r.y< this.player.y)){this.damageEnemy(e,1);}}}
 applyFlame(){if(this.player.weapon!=='flamethrower'||!this.player.laserOn)return;const px=this.player.x,bottom=this.player.y-12;for(const e of this.enemies)if(e.alive){const hit=e.hitRects().some(r=>r.y<bottom&&r.y+r.h>0&&Math.abs((r.x+r.w/2)-px)<Math.max(48,40+(bottom-(r.y+r.h/2))*.22,r.w/2+20));if(hit){e.ignite();if(this.tick%12===0)this.damageEnemy(e,FLAMETHROWER_DAMAGE);}}}
 update(keys){this.tick++;for(const s of this.stars){s.y+=s.sp;if(s.y>HEIGHT){s.x=Math.random()*WIDTH;s.y=0;}}if(this.state!=='play'||this.menuOpen)return;this.playFrames++;if(this.banner>0)this.banner--;this.player.update(keys,this);this.levelFrames++;while(this.weaponSchedule?.length&&this.levelFrames>=this.weaponSchedule[0]){this.weaponSchedule.shift();const k=weighted({gun:48,laser:24,bazooka:10,flamethrower:18});this.pickups.push(new Pickup(k,50+Math.random()*(WIDTH-100),-20));}if(this.healthSchedule.length&&this.levelFrames>=this.healthSchedule[0]&&this.player.lives<MAX_LIVES){this.healthSchedule=[];this.pickups.push(new Pickup('health',50+Math.random()*(WIDTH-100),-20));}if(this.shieldSchedule.length&&this.levelFrames>=this.shieldSchedule[0]){this.shieldSchedule=[];this.pickups.push(new Pickup('shield',50+Math.random()*(WIDTH-100),-20));}if(this.queue.length&&--this.spawnTimer<=0&&this.enemies.length<Math.min(5+this.level,16))this.spawnOne();for(const e of this.enemies){e.update(this);e.burn(this);}for(const a of this.arrows)a.update();for(const b of this.ebullets)b.update();for(const p of this.pickups)p.update();this.applyLaser();this.applyFlame();for(const a of this.arrows)if(a.alive)for(const e of this.enemies)if(a.alive&&e.alive&&e.hitRects().some(r=>overlap(a.box(),r))){a.alive=false;if(e.type==='boss'||e.type==='octopus'||e.type==='snake')this.addScore(10);this.damageEnemy(e,a.damage);if(a.kind==='bazooka')this.rocketBlast(a,e);}const pb=this.player.box();for(const p of this.pickups)if(p.alive&&overlap(pb,p.box())){p.alive=false;this.collect(p);}const hb=this.player.hitbox();for(const b of this.ebullets)if(b.alive&&overlap(hb,b.box())){b.alive=false;this.hurt();}for(const e of this.enemies)if(e.alive&&e.hitRects().some(r=>overlap(hb,r))){if(e.type!=='boss'&&e.type!=='octopus'&&e.type!=='snake')e.alive=false;this.hurt();}this.arrows=this.arrows.filter(x=>x.alive);this.ebullets=this.ebullets.filter(x=>x.alive);this.pickups=this.pickups.filter(x=>x.alive);this.enemies=this.enemies.filter(x=>x.alive);if(this.state==='play'&&!this.queue.length&&!this.enemies.length){if(!this.levelClearTimer){this.levelClearTimer=150;this.addScore(this.level*100);this.audio.sfx(this.level===FINAL_LEVEL?'win':'level_clear');}else if(--this.levelClearTimer<=0){if(this.level===FINAL_LEVEL){this.state='won';this.save();}else this.startLevel(this.level+1);}}}
 timeString(){const s=Math.floor(this.playFrames/FPS);return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s/60)%60).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
}
